version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - rm -f ./gen/sso/*.go
      - protoc --proto_path=proto/sso --go_out=./gen/sso --go_opt=paths=source_relative --go-grpc_out=./gen/sso --go-grpc_opt=paths=source_relative ./proto/sso/*.proto